/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epsi.java.gosecuri;

/**
 *
 * @author mmf
 */
public class CopieTexte extends javax.swing.JFrame {

    /**
     * Creates new form CopieTexte
     */
    public CopieTexte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSaisie = new javax.swing.JLabel();
        jlCopie = new javax.swing.JLabel();
        jbCopie = new javax.swing.JButton();
        jbQuitter = new javax.swing.JButton();
        jtSaisie = new javax.swing.JTextField();
        jtCopie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copie de texte");
        setResizable(false);

        jlSaisie.setText("Zone de saisie");

        jlCopie.setText("Zone de copie");

        jbCopie.setText("Copier");
        jbCopie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCopieActionPerformed(evt);
            }
        });

        jbQuitter.setText("Quitter");
        jbQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitterActionPerformed(evt);
            }
        });

        jtSaisie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSaisieActionPerformed(evt);
            }
        });

        jtCopie.setEditable(false);
        jtCopie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCopieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSaisie)
                        .addGap(18, 18, 18)
                        .addComponent(jtSaisie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCopie)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCopie)
                                .addGap(33, 33, 33)
                                .addComponent(jbQuitter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE))
                            .addComponent(jtCopie))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSaisie)
                    .addComponent(jtSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCopie)
                    .addComponent(jtCopie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbQuitter)
                    .addComponent(jbCopie))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCopieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCopieActionPerformed
        copierTexte();
    }//GEN-LAST:event_jbCopieActionPerformed

    private void jbQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbQuitterActionPerformed

    private void jtSaisieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSaisieActionPerformed
        copierTexte();
    }//GEN-LAST:event_jtSaisieActionPerformed

    private void jtCopieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCopieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCopieActionPerformed

    private void copierTexte() {
        jtCopie.setText(jtSaisie.getText());
        //jtCopie.setText(new Texte("toto").getContenu());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopieTexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopieTexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopieTexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopieTexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CopieTexte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCopie;
    private javax.swing.JButton jbQuitter;
    private javax.swing.JLabel jlCopie;
    private javax.swing.JLabel jlSaisie;
    private javax.swing.JTextField jtCopie;
    private javax.swing.JTextField jtSaisie;
    // End of variables declaration//GEN-END:variables
}
