/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epsi.java.gosecuri;

/**
 *
 * @author Fayçal Ziba
 */
public class Location extends javax.swing.JFrame {

    /**
     * Creates new form Location
     */
    public Location() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        label28 = new java.awt.Label();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label34 = new java.awt.Label();
        label35 = new java.awt.Label();
        Mousquetons28 = new javax.swing.JCheckBox();
        Mousquetons27 = new javax.swing.JCheckBox();
        Mousquetons26 = new javax.swing.JCheckBox();
        Mousquetons25 = new javax.swing.JCheckBox();
        Mousquetons24 = new javax.swing.JCheckBox();
        Mousquetons23 = new javax.swing.JCheckBox();
        Mousquetons22 = new javax.swing.JCheckBox();
        Mousquetons21 = new javax.swing.JCheckBox();
        Mousquetons = new javax.swing.JCheckBox();
        Mousquetons16 = new javax.swing.JCheckBox();
        Mousquetons17 = new javax.swing.JCheckBox();
        Mousquetons18 = new javax.swing.JCheckBox();
        Mousquetons19 = new javax.swing.JCheckBox();
        Mousquetons20 = new javax.swing.JCheckBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label7.setName("mousquetons"); // NOI18N
        label7.setText(" Gants d’intervention");

        label28.setName("mousquetons"); // NOI18N
        label28.setText("Mousquetons");

        label23.setName("mousquetons"); // NOI18N
        label23.setText(" Ceintures de sécurité tactique");

        label24.setName("mousquetons"); // NOI18N
        label24.setText("Détecteurs de métaux");

        label25.setName("mousquetons"); // NOI18N
        label25.setText("Brassards de sécurité");

        label26.setName("mousquetons"); // NOI18N
        label26.setText(" Lampes torches");

        label27.setName("mousquetons"); // NOI18N
        label27.setText(" Bandeaux");

        label29.setName("mousquetons"); // NOI18N
        label29.setText("Gilets pare-balles");

        label30.setName("mousquetons"); // NOI18N
        label30.setText(" Chemises manches courtes");

        label31.setName("mousquetons"); // NOI18N
        label31.setText(" Blousons");

        label32.setName("mousquetons"); // NOI18N
        label32.setText("Coupe-vents ");

        label33.setName("mousquetons"); // NOI18N
        label33.setText(" Talkies walkies");

        label34.setName("mousquetons"); // NOI18N
        label34.setText("Kits oreillettes ");

        label35.setName("mousquetons"); // NOI18N
        label35.setText(" Tasers");

        Mousquetons28.setToolTipText("");
        Mousquetons28.setFocusable(false);
        Mousquetons28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons27.setToolTipText("");
        Mousquetons27.setFocusable(false);
        Mousquetons27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons26.setToolTipText("");
        Mousquetons26.setFocusable(false);
        Mousquetons26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons25.setToolTipText("");
        Mousquetons25.setFocusable(false);
        Mousquetons25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons24.setToolTipText("");
        Mousquetons24.setFocusable(false);
        Mousquetons24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons23.setToolTipText("");
        Mousquetons23.setFocusable(false);
        Mousquetons23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons22.setToolTipText("");
        Mousquetons22.setFocusable(false);
        Mousquetons22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons21.setToolTipText("");
        Mousquetons21.setFocusable(false);
        Mousquetons21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Mousquetons21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mousquetons21ActionPerformed(evt);
            }
        });

        Mousquetons.setToolTipText("");
        Mousquetons.setFocusable(false);
        Mousquetons.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons16.setToolTipText("");
        Mousquetons16.setFocusable(false);
        Mousquetons16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons17.setToolTipText("");
        Mousquetons17.setFocusable(false);
        Mousquetons17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons18.setToolTipText("");
        Mousquetons18.setFocusable(false);
        Mousquetons18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons19.setToolTipText("");
        Mousquetons19.setFocusable(false);
        Mousquetons19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Mousquetons20.setToolTipText("");
        Mousquetons20.setFocusable(false);
        Mousquetons20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mousquetons20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(55, 158, 193));
        jButton1.setText("Identification");
        jButton1.setActionCommand("Identifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButton1)
                            .addGap(335, 335, 335)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(Mousquetons21)
                            .addGap(79, 79, 79)
                            .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(Mousquetons22))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(Mousquetons)
                            .addGap(19, 19, 19)
                            .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(Mousquetons23))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Mousquetons16)
                            .addGap(119, 119, 119)
                            .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Mousquetons24))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(Mousquetons17)
                            .addGap(109, 109, 109)
                            .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Mousquetons25))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(Mousquetons18)
                            .addGap(89, 89, 89)
                            .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(Mousquetons26))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(Mousquetons19)
                            .addGap(99, 99, 99)
                            .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Mousquetons27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Mousquetons20)
                            .addGap(135, 135, 135)
                            .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(Mousquetons28)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButton1))
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons21)
                        .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons22))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons)
                        .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons23))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons16)
                        .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons24))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons17)
                        .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons25))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons18)
                        .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons26))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons19)
                        .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons27))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons20)
                        .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mousquetons28))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Mousquetons21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mousquetons21ActionPerformed
        // TODO add your handling code here:
       // NewOutil mos = new Mousqueton("Mousqueton");
    }//GEN-LAST:event_Mousquetons21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Mousquetons;
    private javax.swing.JCheckBox Mousquetons16;
    private javax.swing.JCheckBox Mousquetons17;
    private javax.swing.JCheckBox Mousquetons18;
    private javax.swing.JCheckBox Mousquetons19;
    private javax.swing.JCheckBox Mousquetons20;
    private javax.swing.JCheckBox Mousquetons21;
    private javax.swing.JCheckBox Mousquetons22;
    private javax.swing.JCheckBox Mousquetons23;
    private javax.swing.JCheckBox Mousquetons24;
    private javax.swing.JCheckBox Mousquetons25;
    private javax.swing.JCheckBox Mousquetons26;
    private javax.swing.JCheckBox Mousquetons27;
    private javax.swing.JCheckBox Mousquetons28;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
